# Centec Phytium BSP Platform modules


PHYTIUM_BSP_MODULE_VERSION = 1.0

export PHYTIUM_BSP_MODULE_VERSION

PHYTIUM_BSP_MODULE = phytium-bsp_$(PHYTIUM_BSP_MODULE_VERSION)_$(PLATFORM_ARCH).deb

$(PHYTIUM_BSP_MODULE)_SRC_PATH = $(PLATFORM_PATH)/phytium-bsp
$(PHYTIUM_BSP_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(PHYTIUM_BSP_MODULE)
