# Centec PHYTIUM_8T6S10X2C Platform modules
CENTEC_PHYTIUM_8T6S10X2C_PLATFORM_MODULE_VERSION =1.0
export CENTEC_PHYTIUM_8T6S10X2C_PLATFORM_MODULE_VERSION

CENTEC_PHYTIUM_8T6S10X2C_PLATFORM_MODULE = platform-modules-phytium-8t6s10x2c_$(CENTEC_PHYTIUM_8T6S10X2C_PLATFORM_MODULE_VERSION)_arm64.deb

$(CENTEC_PHYTIUM_8T6S10X2C_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-phytium
$(CENTEC_PHYTIUM_8T6S10X2C_PLATFORM_MODULE)_PLATFORM = arm64-centec_phytium_8t6s10x2c-r0
$(CENTEC_PHYTIUM_8T6S10X2C_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(CENTEC_PHYTIUM_8T6S10X2C_PLATFORM_MODULE)
