SOM_VERSION = 1.0
SOM_PKG_NAME = som

export SOM_VERSION SOM_PKG_NAME

SOM = $(SOM_PKG_NAME)_$(SOM_VERSION)_$(CONFIGURED_ARCH).deb
$(SOM)_SRC_PATH = $(SRC_PATH)/$(SOM_PKG_NAME)
$(SOM)_DEPENDS = $(LIBSWSSCOMMON_DEV)
$(SOM)_RDEPENDS = $(LIBSWSSCOMMON)

SONIC_DPKG_DEBS += $(SOM)

SOM_DBG = $(SOM_PKG_NAME)-dbgsym_$(SOM_VERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(SOM),$(SOM_DBG)))

export SOM SOM_DBG